# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-07-10 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_faq", "0001_initial"),
        ("django_faq", "0002_faqitemt9n_url_key"),
    ]

    dependencies = [
        ("django_regional", "0002_reset_pk_sequences"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqChannel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "default_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="django_regional.language",
                    ),
                ),
                ("languages", models.ManyToManyField(blank=True, related_name="+", to="django_regional.language")),
            ],
            options={
                "db_table": "faq_channel",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FaqGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("channels", models.ManyToManyField(blank=True, related_name="groups", to="django_faq.faqchannel")),
            ],
            options={
                "db_table": "faq_group",
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="FaqItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("url_key", models.CharField(db_index=True, max_length=128, unique=True)),
                ("question", models.CharField(max_length=512)),
                ("answer", models.TextField()),
                ("short_answer", models.CharField(blank=True, default="", max_length=512)),
                ("image", models.ImageField(blank=True, null=True, upload_to="faq/")),
                ("position", models.PositiveIntegerField(default=0)),
                ("position_in_group", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="django_faq.faqgroup",
                    ),
                ),
            ],
            options={
                "db_table": "faq_item",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="FaqAssociation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("category", "Category"),
                            ("blog-post", "Blog Post"),
                            ("page", "Page"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_identifier", models.CharField(max_length=128)),
                (
                    "faq_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations",
                        to="django_faq.faqitem",
                    ),
                ),
            ],
            options={
                "db_table": "faq_association",
            },
        ),
        migrations.CreateModel(
            name="FaqItemT9N",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "url_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Per-language SEO slug. Empty = fall back to base FaqItem.url_key.",
                        max_length=128,
                    ),
                ),
                ("question", models.CharField(max_length=512)),
                ("answer", models.TextField()),
                ("short_answer", models.CharField(blank=True, default="", max_length=512)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="django_faq.faqitem",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="django_regional.language"
                    ),
                ),
            ],
            options={
                "db_table": "faq_item_t9n",
            },
        ),
        migrations.CreateModel(
            name="FaqGroupT9N",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="django_faq.faqgroup",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="django_regional.language"
                    ),
                ),
            ],
            options={
                "db_table": "faq_group_t9n",
                "constraints": [
                    models.UniqueConstraint(fields=("group", "language"), name="unique_faq_group_language")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="faqitem",
            index=models.Index(fields=["group", "position_in_group"], name="faq_item_group_i_2db5bb_idx"),
        ),
        migrations.AddIndex(
            model_name="faqitem",
            index=models.Index(fields=["is_active"], name="faq_item_is_acti_4d8957_idx"),
        ),
        migrations.AddConstraint(
            model_name="faqassociation",
            constraint=models.UniqueConstraint(
                fields=("faq_item", "entity_type", "entity_identifier"), name="unique_faq_association"
            ),
        ),
        migrations.AddConstraint(
            model_name="faqitemt9n",
            constraint=models.UniqueConstraint(fields=("item", "language"), name="unique_faq_item_language"),
        ),
        migrations.AddConstraint(
            model_name="faqitemt9n",
            constraint=models.UniqueConstraint(
                condition=models.Q(("url_key", ""), _negated=True),
                fields=("language", "url_key"),
                name="unique_faq_t9n_url_key_per_language",
            ),
        ),
    ]
